/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gspal
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        casa3 = new javax.swing.JButton();
        casa1 = new javax.swing.JButton();
        casa2 = new javax.swing.JButton();
        casa4 = new javax.swing.JButton();
        casa5 = new javax.swing.JButton();
        casa6 = new javax.swing.JButton();
        casa7 = new javax.swing.JButton();
        casa8 = new javax.swing.JButton();
        casa9 = new javax.swing.JButton();
        txtIP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        casa3.setBackground(new java.awt.Color(204, 255, 255));
        casa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa3ActionPerformed(evt);
            }
        });
        getContentPane().add(casa3);
        casa3.setBounds(531, 217, 150, 150);

        casa1.setBackground(new java.awt.Color(204, 255, 255));
        casa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa1ActionPerformed(evt);
            }
        });
        getContentPane().add(casa1);
        casa1.setBounds(195, 217, 150, 150);

        casa2.setBackground(new java.awt.Color(204, 255, 255));
        casa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa2ActionPerformed(evt);
            }
        });
        getContentPane().add(casa2);
        casa2.setBounds(363, 217, 150, 150);

        casa4.setBackground(new java.awt.Color(204, 255, 255));
        casa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa4ActionPerformed(evt);
            }
        });
        getContentPane().add(casa4);
        casa4.setBounds(195, 385, 150, 150);

        casa5.setBackground(new java.awt.Color(204, 255, 255));
        casa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa5ActionPerformed(evt);
            }
        });
        getContentPane().add(casa5);
        casa5.setBounds(363, 385, 150, 150);

        casa6.setBackground(new java.awt.Color(204, 255, 255));
        casa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa6ActionPerformed(evt);
            }
        });
        getContentPane().add(casa6);
        casa6.setBounds(531, 385, 150, 150);

        casa7.setBackground(new java.awt.Color(204, 255, 255));
        casa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa7ActionPerformed(evt);
            }
        });
        getContentPane().add(casa7);
        casa7.setBounds(195, 553, 150, 150);

        casa8.setBackground(new java.awt.Color(204, 255, 255));
        casa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa8ActionPerformed(evt);
            }
        });
        getContentPane().add(casa8);
        casa8.setBounds(363, 553, 150, 150);

        casa9.setBackground(new java.awt.Color(204, 255, 255));
        casa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa9ActionPerformed(evt);
            }
        });
        getContentPane().add(casa9);
        casa9.setBounds(531, 553, 150, 150);

        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });
        getContentPane().add(txtIP);
        txtIP.setBounds(195, 95, 150, 24);

        jLabel1.setText("IP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(195, 72, 10, 16);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(363, 94, 150, 26);

        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(363, 72, 40, 16);

        btnLogin.setText("Logar");
        getContentPane().add(btnLogin);
        btnLogin.setBounds(531, 96, 150, 23);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 140, 490, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa3ActionPerformed

    private void casa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa1ActionPerformed

    private void casa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa2ActionPerformed

    private void casa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa4ActionPerformed

    private void casa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa5ActionPerformed

    private void casa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa6ActionPerformed

    private void casa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa7ActionPerformed

    private void casa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa8ActionPerformed

    private void casa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casa9ActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton casa1;
    private javax.swing.JButton casa2;
    private javax.swing.JButton casa3;
    private javax.swing.JButton casa4;
    private javax.swing.JButton casa5;
    private javax.swing.JButton casa6;
    private javax.swing.JButton casa7;
    private javax.swing.JButton casa8;
    private javax.swing.JButton casa9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
